### PR TITLE
Added additional data parameter to Client::userReportMake()

### PR DESCRIPTION
**Pull request by de-salvatierra**

### CODE REVIEW

**Comment by tarampampam** [comment]
@de-salvatierra Hi! Can you describe use-case for this changes?

**Comment by de-salvatierra** [comment]
> @de-salvatierra Hi! Can you describe use-case for this changes?

Hello. There is a need to send such requests:

```
{
  "queryType": "MULTIPART",
  "query": " ",
  "data": {
    "phone": "9001234567"
  }
}
```

**Comment by tarampampam** [comment]
Ok, I will check the docs. Can you write unit-tests for your changes? Anyway without tests changes cannot be accepted

**Comment by tarampampam** [comment]
@de-salvatierra Tests were written by me, fresh release: https://github.com/avtocod/b2b-api-php/releases/tag/v3.3.0

Thx for your contribution! :+1:

**Pull request merged**
